"""Golden master for construct_ffmpeg_command / src.ffmpeg_command.build()
(tech-debt-audit-2026-08-02.md item 6).

RULES FOR EDITING THIS FILE:

1. This file changes only as its own commit, never bundled with a feature
   commit. Feature work must make it fail first (red); a *separate* commit
   updates the case(s) and turns it green, naming which case(s) changed and
   why in one sentence.
2. Every changed line needs a reason, not a re-run. Never regenerate all
   cases from build()'s live output and diff them in bulk -- that is
   exactly the failure mode this file exists to catch. Edit by hand: open
   the specific case(s) the new feature touches, change only those lines,
   leave every other line byte-identical. A case nobody meant to touch
   changing is a regression signal -- stop and find out why before
   accepting it.
3. Cases are formatted one argument per line on purpose: a diff on a
   one-flag-per-line list shows exactly which argument moved.
4. A new dimension (new encoder, new ConversionRequest field, new branch)
   gets new Case entries, not edits to existing ones -- existing cases keep
   asserting exactly what they always asserted, including the default value
   of the new field/branch.

See src/pro/ARCHITECTURE.md's "Golden master protocol" section for the
narrative version of this rule and why it exists.
"""
from __future__ import annotations

import os
import sys
import unittest
from dataclasses import dataclass
from unittest.mock import patch

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

from src.conversion import ConversionManager, ConversionRequest  # noqa: E402
from src.utils import (FFMPEG_CONVERT_FILTER, FFMPEG_EXECUTABLE,  # noqa: E402
                       get_lut_filter_path, build_libplacebo_filter)
from _recording_view import RecordingConversionView  # noqa: E402


_PROPS = dict(width=1920, height=1080, bit_rate=4_000_000, codec_name='h264',
              frame_rate=30.0, audio_codec='aac', audio_bit_rate=128000,
              duration=120.0, subtitle_streams=[])


def _req(**overrides) -> ConversionRequest:
    base = dict(input_path='in.mp4', output_path='out.mkv', gamma=1.0,
                use_gpu=False, open_after_conversion=False)
    base.update(overrides)
    return ConversionRequest(**base)


def zscale_filter(gamma: float, tonemapper: str) -> str:
    """The CPU (non-libplacebo) tonemap filter body, same call the real
    zscale path in construct_ffmpeg_command makes."""
    return FFMPEG_CONVERT_FILTER.format(gamma=gamma, tonemapper=tonemapper,
                                        lut_path=get_lut_filter_path())


def libplacebo_filter(gamma: float, tonemapper: str, cuda_input: bool,
                      lut_enabled: bool) -> str:
    """The GPU (libplacebo) tonemap filter body, same call the real
    libplacebo path in construct_ffmpeg_command makes."""
    return build_libplacebo_filter(gamma, tonemapper, cuda_input=cuda_input,
                                   lut_enabled=lut_enabled)


def _FC(inner: str) -> str:
    """The [0:v:0]...[vout] frame construct_ffmpeg_command always wraps the
    tonemap filter body in."""
    return f'[0:v:0]{inner}[vout]'


@dataclass(frozen=True)
class Case:
    name: str
    request_kwargs: dict
    props_kwargs: dict
    expect_notices: int
    expect_raises: str | None
    expect: list | None
    platform: str = 'Windows'
    libplacebo: bool = True
    interop: bool = True
    gpu_encoder: str | None = None
    gpu_probe_forbidden: bool = False


CASES = [
    Case(
        name='cpu_baseline_mkv_cq_8bit_h264',
        request_kwargs={},
        props_kwargs={},
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_nvenc_no_libplacebo_windows',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-hwaccel',
            'cuda',
            '-hwaccel_device',
            '0',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_nvenc_libplacebo_interop_windows',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'cuda=cu:0',
            '-init_hw_device',
            'vulkan=vk@cu',
            '-hwaccel',
            'cuda',
            '-hwaccel_output_format',
            'cuda',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(1.0, 'reinhard', True, True)),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_qsv_no_libplacebo_windows',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_qsv',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-hwaccel',
            'qsv',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_qsv',
            '-global_quality',
            '23',
            '-b:v',
            '4000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_qsv_darwin_unsupported',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        platform='Darwin',
        libplacebo=False,
        gpu_encoder='h264_qsv',
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_nvenc_darwin_unsupported',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        platform='Darwin',
        libplacebo=False,
        gpu_encoder='h264_nvenc',
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_amf_windows_supported',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_amf',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_amf',
            '-quality',
            'balanced',
            '-rc',
            'cqp',
            '-qp_i',
            '23',
            '-qp_p',
            '23',
            '-qp_b',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_amf_darwin_unsupported',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        platform='Darwin',
        libplacebo=False,
        gpu_encoder='h264_amf',
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='gpu_unknown_encoder_windows',
        request_kwargs={'use_gpu': True},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_mystery',
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bit_depth_10_cpu_mkv',
        request_kwargs={'bit_depth': 10},
        props_kwargs={},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p10le',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bit_depth_12_forces_cpu_no_probe',
        request_kwargs={'use_gpu': True, 'bit_depth': 12},
        props_kwargs={},
        libplacebo=False,
        gpu_probe_forbidden=True,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx265',
            '-preset',
            'veryfast',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p12le',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bit_depth_10_gpu_nvenc_hevc_swap',
        request_kwargs={'use_gpu': True, 'bit_depth': 10},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-hwaccel',
            'cuda',
            '-hwaccel_device',
            '0',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'hevc_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'p010le',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='source_hevc_cpu_preserve_mkv',
        request_kwargs={},
        props_kwargs={'codec_name': 'hevc'},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx265',
            '-preset',
            'veryfast',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='source_hevc_cpu_preserve_mp4_tag',
        request_kwargs={'output_path': 'out.mp4'},
        props_kwargs={'codec_name': 'hevc'},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-c:v',
            'libx265',
            '-preset',
            'veryfast',
            '-crf',
            '23',
            '-tag:v',
            'hvc1',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mp4',
            '-y',
        ],
    ),
    Case(
        name='source_hevc_gpu_nvenc_swap_8bit',
        request_kwargs={'use_gpu': True},
        props_kwargs={'codec_name': 'hevc'},
        libplacebo=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-hwaccel',
            'cuda',
            '-hwaccel_device',
            '0',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'hevc_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='dovi_profile5_no_libplacebo_warns',
        request_kwargs={},
        props_kwargs={'is_dolby_vision': True, 'dovi_profile': 5},
        libplacebo=False,
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a:0?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'aac',
            '-ac',
            '2',
            '-b:a',
            '192k',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='dovi_profile5_libplacebo_available_gpu_unchecked',
        request_kwargs={'use_gpu': False},
        props_kwargs={'is_dolby_vision': True, 'dovi_profile': 5},
        interop=False,
        expect_notices=1,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'vulkan=vk:0',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(1.0, 'reinhard', False, True)),
            '-map',
            '[vout]',
            '-map',
            '0:a:0?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'aac',
            '-ac',
            '2',
            '-b:a',
            '192k',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='dovi_profile7_free_tier_downmix',
        request_kwargs={'licensed': False},
        props_kwargs={'is_dolby_vision': True, 'dovi_profile': 7},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a:0?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'aac',
            '-ac',
            '2',
            '-b:a',
            '192k',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='dovi_profile7_licensed_passthrough',
        request_kwargs={'licensed': True},
        props_kwargs={'is_dolby_vision': True, 'dovi_profile': 7},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='mp4_audio_transcode_subtitle_drop',
        request_kwargs={'output_path': 'out.mp4'},
        props_kwargs={'audio_codec': 'dts', 'audio_bit_rate': 768000, 'subtitle_streams': [{'index': 2, 'codec_name': 'subrip'}, {'index': 3, 'codec_name': 'hdmv_pgs_subtitle'}]},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:2',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'aac',
            '-b:a',
            '384000',
            '-c:s',
            'mov_text',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mp4',
            '-y',
        ],
    ),
    Case(
        name='mp4_audio_copy_ok_text_subtitle',
        request_kwargs={'output_path': 'out.mp4'},
        props_kwargs={'audio_codec': 'aac', 'subtitle_streams': [{'index': 2, 'codec_name': 'mov_text'}]},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:2',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-crf',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'mov_text',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mp4',
            '-y',
        ],
    ),
    Case(
        name='mov_hevc_source_tag',
        request_kwargs={'output_path': 'out.mov'},
        props_kwargs={'codec_name': 'hevc'},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-c:v',
            'libx265',
            '-preset',
            'veryfast',
            '-crf',
            '23',
            '-tag:v',
            'hvc1',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mov',
            '-y',
        ],
    ),
    Case(
        name='bitrate_mode_cpu_libx264',
        request_kwargs={'quality': 6000, 'quality_mode': 'bitrate'},
        props_kwargs={},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx264',
            '-preset',
            'veryfast',
            '-tune',
            'film',
            '-b:v',
            '6000000',
            '-maxrate',
            '9000000',
            '-bufsize',
            '12000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bitrate_mode_nvenc',
        request_kwargs={'use_gpu': True, 'quality': 8000, 'quality_mode': 'bitrate'},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-hwaccel',
            'cuda',
            '-hwaccel_device',
            '0',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-b:v',
            '8000000',
            '-maxrate',
            '12000000',
            '-bufsize',
            '16000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bitrate_mode_amf_vbr_peak',
        request_kwargs={'use_gpu': True, 'quality': 8000, 'quality_mode': 'bitrate'},
        props_kwargs={},
        libplacebo=False,
        gpu_encoder='h264_amf',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_amf',
            '-quality',
            'balanced',
            '-rc',
            'vbr_peak',
            '-b:v',
            '8000000',
            '-maxrate',
            '12000000',
            '-bufsize',
            '16000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='bitrate_mode_libx265_12bit',
        request_kwargs={'use_gpu': True, 'bit_depth': 12, 'quality': 10000, 'quality_mode': 'bitrate'},
        props_kwargs={},
        libplacebo=False,
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(zscale_filter(1.0, 'reinhard')),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'libx265',
            '-preset',
            'veryfast',
            '-b:v',
            '10000000',
            '-maxrate',
            '15000000',
            '-bufsize',
            '20000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p12le',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='libplacebo_lut_disabled_gamma_identity',
        request_kwargs={'use_gpu': True, 'lut_enabled': False},
        props_kwargs={},
        interop=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'vulkan=vk:0',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(1.0, 'reinhard', False, False)),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='libplacebo_lut_enabled_gamma_nonidentity',
        request_kwargs={'gamma': 2.2, 'use_gpu': True},
        props_kwargs={},
        interop=False,
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'vulkan=vk:0',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(2.2, 'reinhard', False, True)),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='dovi_profile5_gpu_only_tonemapper_raises',
        request_kwargs={'tonemapper': 'bt.2390'},
        props_kwargs={'is_dolby_vision': True, 'dovi_profile': 5},
        libplacebo=False,
        expect_notices=1,
        expect_raises="bt.2390 requires GPU tonemapping; this item's settings force CPU processing — change the tonemapper or output bit depth.",
        expect=None,
    ),
    Case(
        name='cuda_interop_fully_gpu_fast_path',
        request_kwargs={'use_gpu': True, 'lut_enabled': False},
        props_kwargs={},
        gpu_encoder='h264_nvenc',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'cuda=cu:0',
            '-init_hw_device',
            'vulkan=vk@cu',
            '-hwaccel',
            'cuda',
            '-hwaccel_output_format',
            'cuda',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(1.0, 'reinhard', True, False)),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_nvenc',
            '-preset',
            'p4',
            '-tune',
            'hq',
            '-rc',
            'vbr',
            '-cq',
            '23',
            '-b:v',
            '4000000',
            '-maxrate',
            '4000000',
            '-bufsize',
            '8000000',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
    Case(
        name='plain_vulkan_gamma_identity_skip_eq',
        request_kwargs={'use_gpu': True, 'lut_enabled': False},
        props_kwargs={},
        interop=False,
        gpu_encoder='h264_amf',
        expect_notices=0,
        expect_raises=None,
        expect=[
            FFMPEG_EXECUTABLE,
            '-loglevel',
            'info',
            '-init_hw_device',
            'vulkan=vk:0',
            '-filter_hw_device',
            'vk',
            '-i',
            'in.mp4',
            '-filter_complex',
            _FC(libplacebo_filter(1.0, 'reinhard', False, False)),
            '-map',
            '[vout]',
            '-map',
            '0:a?',
            '-map',
            '0:s?',
            '-c:v',
            'h264_amf',
            '-quality',
            'balanced',
            '-rc',
            'cqp',
            '-qp_i',
            '23',
            '-qp_p',
            '23',
            '-qp_b',
            '23',
            '-r',
            '30.0',
            '-pix_fmt',
            'yuv420p',
            '-strict',
            '-2',
            '-c:a',
            'copy',
            '-c:s',
            'copy',
            '-map_metadata',
            '0',
            '-movflags',
            '+faststart',
            'out.mkv',
            '-y',
        ],
    ),
]


class TestFfmpegCommandGoldenMaster(unittest.TestCase):
    """One case per branch of construct_ffmpeg_command as it exists before
    the item-6 split (audit item 6). Every case here must stay green
    throughout Tasks 2-7 -- it is what proves the split is behavior-
    preserving. See the module docstring for the edit rules."""

    def _run(self, case: Case) -> None:
        manager = ConversionManager()
        if case.gpu_encoder is not None:
            manager._gpu_encoder = case.gpu_encoder
        if case.gpu_probe_forbidden:
            def _forbidden():
                raise AssertionError(
                    f'{case.name}: detect_gpu_encoder must not be called -- '
                    f'a 12-bit request forces use_gpu off before the GPU '
                    f'vendor probe would run')
            manager.detect_gpu_encoder = _forbidden  # type: ignore[method-assign]
        request = _req(**case.request_kwargs)
        properties = dict(_PROPS, **case.props_kwargs)
        view = RecordingConversionView()
        with patch('src.conversion.platform.system', return_value=case.platform), \
             patch('src.conversion.vulkan_libplacebo_available', return_value=case.libplacebo), \
             patch('src.conversion.vulkan_cuda_interop_available', return_value=case.interop):
            if case.expect_raises is not None:
                with self.assertRaises(ValueError, msg=case.name) as ctx:
                    manager.construct_ffmpeg_command(request, properties, view)
                self.assertEqual(str(ctx.exception), case.expect_raises, msg=case.name)
            else:
                cmd = manager.construct_ffmpeg_command(request, properties, view)
                self.assertEqual(cmd, case.expect, msg=case.name)
        self.assertEqual(len(view.notices), case.expect_notices, msg=case.name)

    def test_golden_cases(self) -> None:
        for case in CASES:
            with self.subTest(case=case.name):
                self._run(case)

    def test_every_case_name_is_unique(self) -> None:
        names = [c.name for c in CASES]
        self.assertEqual(len(names), len(set(names)),
                         msg='duplicate case name -- subTest would silently '
                             'merge two different cases under one label')


if __name__ == '__main__':
    unittest.main()
